### ISSUE TITLE
blank settings file

### ISSUE THREAD

**Issue by jfmherokiller** [unknown321/mgsv_emulator#1]
please add a blank settings.py file because its not easy to figure out what properties are missing

**Comment by unknown321** [comment]
by blank you mean completely empty one?

**Comment by jfmherokiller** [comment]
yes, I do because trying to run the emulator fails without settings.py

**Comment by unknown321** [comment]
It will fail even with settings.py, because there is a separate file with default request return values. Most of those values relate to my steam account and I don't want them to be shared on the internet.
You will also need an encryption key, which is not present in this repository (and won't be).

Right now, server part works only on my machine in half-working state. I will release missing files when it's done.

**Comment by jfmherokiller** [comment]
could you release the hash of the static key or a script to extract it so that it can be retrieved by others?
