### ISSUE TITLE
Nuke counts from other platforms?

### ISSUE THREAD

**Issue by alissonmuller** [unknown321/mgsv_emulator#10]
I was wondering, would it be possible to put the nuke counts from the other platforms, on the MGSV Nuke Watcher page?
What would be needed?

**Comment by unknown321** [comment]
It is impossible, because konami uses different keys for encryption on different platforms. Key for PC was extracted through reverse engineering and it happened to be the same as ps3 one - doesn't work on other platforms (xbox360, ps4, xbone), I tried. Therefore, emulator works only for ps3 and pc. Theoretically it could be possible if we had a xbox/ps debugger, but we don't.

**Comment by alissonmuller** [comment]
I made some testing, and it seems that the same encryption key does work on ps4.
Also, CMD_GET_ABOLITION_COUNT apparently doesn't need a login or session key (it works with `'session_crypto': False, 'session_key': ''`).

**Comment by alissonmuller** [comment]
About 360 and one, I noticed that if I use an incorrect encryption key, the script fails with an `JSONDecodeError` exception. But if I use the same encryption key from the other platforms, only the request fails, with a `403` status.
I wonder if Konami really uses a different key on the Xboxes, or maybe there are extra request headers/parameters or something on those platforms... What do you think?

**Comment by unknown321** [comment]
Yep, you are right about ps4. Guess something changed on their side or maybe it was like that all the time. Added to the site, thanks.

About 360 and one: 
  - JSONDecodeError occurs when decoded data cannot be decoded into json (because your key is incorrect, duh).
  - 360 most likely has something different in headers (maybe xbox live id?), user client or something like that - can't say for sure without an example of successful request. As for steam and ps3/4 - they don't have anything platform-specific. There is a way to figure that out - set up a proxy between xbox and the internet, dump all requests, decode them using the key and inspect. Unfortunately I don't have xbox and time to investigate, so it is up to community.
