### ISSUE TITLE
How to provide credentials in settings.py?

### ISSUE THREAD

**Issue by alissonmuller** [unknown321/mgsv_emulator#6]
How can I get the steam_id, magic_hash, and static_key? Can someone give some tips, please?
Also, should I put those credentials on settings.py, or provide them as kwargs on Client().login()?

**Comment by unknown321** [comment]
Steam_id and magic_hash are returned by konami servers as a response to CMD_AUTH_STEAMTICKET command; there is no way to get them without sending a request to konami. 

About static key - I am not going to make it public, at least until Survive releases. With it you can send anything to konami servers - a big opportunity for cheaters. You can try to pull static_key from mgsvtpp.exe, just like I did.

Currently I am working on rewriting code in order to improve structure and allow more extensibility. I am going to add some instructions after I finish porting basic stuff like client emulation and logging in. You can keep track of my progress here - https://github.com/unknown321/mgsv_emulator/tree/v2

**Comment by alissonmuller** [comment]
I think I found steam_id and magic_hash, on a response to CMD_REQAUTH_HTTPS command.
I provided them on settings.py (STEAM_ID and MAGIC_HASH), but I also had to provide some other missing variables (as None).
Here's my settings.py, is this correct?
```python
STEAM_TICKET = None
STEAM_TICKET_SIZE = None

NPTICKET = None
NP_TICKET_SIZE = None

MAGIC_HASH = "<magic_hash>"
STEAM_ID = "<steam_id>"

PS3_PSN_ID = None

EX_IP = None
IN_IP = None

STATIC_KEY_FILE_PATH = "static_key.bin"

LOG_PATH = "log.txt"
LOG_FORMAT = "{curdate} {event_type} {data}\n"
```

**Comment by unknown321** [comment]
Other variables are not needed, you should be fine.
